<strong>numpy的引入-代数运算</strong>

In [1]:
#导入numpy第三方库
import numpy as np

In [3]:
#生成numpy数组,可以自指定数据类型
a = np.array([1,2,3],dtype = np.float16)
print(a)
type(a)
#发现变量类型为ndarray

[1. 2. 3.]


numpy.ndarray

In [4]:
#numpy的算术运算,数组大小一样(当不能广播时)
a = np.array([1,2,3])
b = np.array([2,3,4])

#加减法与矩阵加减一样,但是乘除不一样,只是对应位置的元素进行操作
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[3 5 7]
[-1 -1 -1]
[ 2  6 12]
[0.5        0.66666667 0.75      ]


In [5]:
#numpy的广播作用
a = np.array([4,6,8])
k = 4
print(k*a)

#相当于把k = 4自动广播到[4,4,4]

[16 24 32]


In [6]:
#numpy的N维数组
a = np.array([[1,2],[3,4]])

print(a)
print(type(a))#变量类型
print(a.dtype)#数据类型
print(a.shape)#数组纬度,即a的形状


#高纬度也可以进行广播
print(10*a)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
int64
(2, 2)
[[10 20]
 [30 40]]


In [7]:
#广播的拓展
#本质是矩阵的自动调整到可以形状相同,以到达进行矩阵运算的目的

a = np.array([[1,2],[3,4]])
b = np.array([3,4])

#b被自动拓展为[[3,4],[3,4]]
print(a*b)

[[ 3  8]
 [ 9 16]]


In [8]:
#numpy数组的访问
a = np.array([[1,2],[3,4],[5,6]])

#下标访问:索引从0开始
print(a[0][1])
print(a[2][0])

#循环访问每一行
for row in a:
    print(row)

2
5
[1 2]
[3 4]
[5 6]


In [9]:
#numpy展开为一维

a = np.array([[1,2],[3,4],[5,6]])
flat = a.flatten()
print(flat)
print(type(flat))

#获取索引为1,3,5的元素(要展开后才能这样做,确保不溢出,或者索引小一点)
x = flat[np.array([1,3,5])]
print(x)

x = a[np.array([0,2])]
print(x)

#常用做法:实现提取满足特定要求的元素
choose = flat > 3
print(choose)
print(flat[choose])

#或者更一般
print(flat[flat > 3])

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
[2 4 6]
[[1 2]
 [5 6]]
[False False False  True  True  True]
[4 5 6]
[4 5 6]


<strong>numpy的引入-矩阵运算</strong>

In [10]:
#导入包
import numpy as np
import matplotlib.pyplot as plt

In [11]:
#多维数组的引入

a = np.array([[1,2],[3,4]])

print(np.ndim(a))#输出数组纬度
print(a.shape)#输出数组形状

#一般二维数组被称为矩阵

2
(2, 2)


In [12]:
#矩阵的乘法:纬度要对应

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A.shape,B.shape)

ANS = np.dot(A,B)#dot为点的意思,故为点乘,即矩阵乘积
print(ANS)

(2, 2) (2, 2)
[[19 22]
 [43 50]]


In [13]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[1,2],[2,3]])
print(A.shape,B.shape)

ANS = np.dot(A,B)
print(ANS)

(3, 2) (2, 2)
[[ 5  8]
 [11 18]
 [17 28]]


In [19]:
#只有一个纬度的某个意义上不叫矩阵,但是可以进行计算
#另外，当A是二维矩阵、B是一维数组时,对应维度的元素个数要保持一致的原则依然成立

A = np.array([[1,2],[3,4],[5,6]])

B = np.array([1,2])      #一个纬度一定要匹配纬度,放左边等价于1x2,放右边等于2x1
C = np.array([[1],[2],[3]])
print(A.shape,B.shape,C.shape)

ANS = np.dot(A,B)
print(ANS)
print(ANS.shape)

# 错误用法
ANS = np.dot(C,B)
print(ANS)


(3, 2) (2,) (3, 1)
[ 5 11 17]
(3,)


ValueError: shapes (3,1) and (2,) not aligned: 1 (dim 1) != 2 (dim 0)

In [ ]:
#神经网络的内积

A = np.array([4,5])
B = np.array([[1,2,4],[2,3,5]])

print(A.shape,B.shape)

ANS = np.dot(A,B)
print(ANS)
print(ANS.shape)

(2,) (2, 3)
[14 23 41]
(3,)


In [ ]:
#numpy的最值处理

# 一维
x = np.array([1,2,3,4,5])
maxn = np.max(x) # 获取最大值
maxn_index = np.argmax(x) #获取矩阵最大值索引
print(maxn,maxn_index)

# 多维
x = np.array([[1,2],[3,4]])
maxn = np.max(x) # 获取最大值
maxn_index = np.argmax(x) #获取矩阵最大值索引
print(maxn,maxn_index)

#发现这样处理自动展开成一维处理了,不是我们想要的

5 4
4 3


In [ ]:
# 特殊处理方法
x = np.array([[1,2],[3,4]])
maxn = np.max(x,axis = 1)
maxn_index = np.argmax(x,axis = 1) #axis = 0表示列,axis = 1表示行
print(maxn,maxn_index)

#sum也是同理的
sum = np.sum(x,axis = 1)
print(sum)

[2 4] [1 1]
[3 7]


In [ ]:
# 计算矩阵中元素总数
x = np.random.randint(0,5,(5,5))
print(x.shape)
print(len(x))
print(x.size)

(5, 5)
5
25
