### **本节将介绍torch中文件的读写**

In [37]:
# 导入包
import torch
from torch import nn
import torch.nn.functional as F
import os

**一，张量tensor的读写**

In [38]:
# 单一tensor保存与读入
save_dir = "data"
x1_save = torch.tensor([1,2,3])
torch.save(x1_save,os.path.join(save_dir,'x1_file'))
x1 = torch.load(os.path.join(save_dir,'x1_file'))
print(x1)

tensor([1, 2, 3])


C:\Users\28718\AppData\Local\Temp\ipykernel_1084\3623856389.py:5: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  x1 = torch.load(os.path.join(save_dir,'x1_file'))


In [39]:
# tensor列表保存
x_list_save = torch.tensor([[1,2,3],[4,5,6]])
torch.save(x_list_save,os.path.join(save_dir,'x_list_file'))
x_list = torch.load(os.path.join(save_dir,'x_list_file'))
print(x_list)

tensor([[1, 2, 3],
        [4, 5, 6]])


C:\Users\28718\AppData\Local\Temp\ipykernel_1084\170558417.py:4: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  x_list = torch.load(os.path.join(save_dir,'x_list_file'))


In [40]:
# torch字典保存
my_dict = {'x' : x1_save,'x_list' : x_list_save}
torch.save(my_dict,os.path.join(save_dir,'dict_file'))
mydict2 = torch.load(os.path.join(save_dir,'dict_file'))
print(mydict2)

{'x': tensor([1, 2, 3]), 'x_list': tensor([[1, 2, 3],
        [4, 5, 6]])}


C:\Users\28718\AppData\Local\Temp\ipykernel_1084\2459168235.py:4: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  mydict2 = torch.load(os.path.join(save_dir,'dict_file'))


**二，加载与保存模型参数**

保存单个权重向量（或其他张量）确实有用，
但是如果我们想保存整个模型，并在以后加载它们，
单独保存每个向量则会变得很麻烦。
毕竟，我们可能有数百个参数散布在各处。
因此，深度学习框架提供了内置函数来保存和加载整个网络。
需要注意的一个重要细节是，这将保存模型的参数而不是保存整个模型。
例如，如果我们有一个3层多层感知机，我们需要单独指定架构。
因为模型本身可以包含任意代码，所以模型本身难以序列化。
因此，为了恢复模型，我们需要用代码生成架构，
然后从磁盘加载参数。
让我们从熟悉的多层感知机开始尝试一下。

In [41]:
# 简单的多层感知机
class Mulpre(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear1 = nn.Linear(10,20)
        self.linear2 = nn.Linear(20,10)

    def forward(self,x):
        return self.linear2(F.relu(self.linear1(x)))

In [44]:
model = Mulpre()
x = torch.rand(2,10)
y = model(x)
print(y)

tensor([[ 0.0069, -0.1141, -0.2908, -0.1686,  0.3785,  0.1223, -0.0792, -0.1214,
         -0.1187, -0.0279],
        [-0.0052,  0.0116, -0.2205, -0.1482,  0.3257,  0.1411,  0.0374, -0.0467,
         -0.1561, -0.0512]], grad_fn=<AddmmBackward0>)


In [45]:
# 保存参数
torch.save(model.state_dict(),"data/Mulpre.params")

In [46]:
# 读取参数
model_new = Mulpre()
model_new.load_state_dict(torch.load("data/Mulpre.params"))
y2 = model_new(x)
print(y2)

tensor([[ 0.0069, -0.1141, -0.2908, -0.1686,  0.3785,  0.1223, -0.0792, -0.1214,
         -0.1187, -0.0279],
        [-0.0052,  0.0116, -0.2205, -0.1482,  0.3257,  0.1411,  0.0374, -0.0467,
         -0.1561, -0.0512]], grad_fn=<AddmmBackward0>)


C:\Users\28718\AppData\Local\Temp\ipykernel_1084\3668907764.py:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model_new.load_state_dict(torch.load("data/Mulpre.params"))


In [ ]:
# 对比结果
print(y == y2)

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])
