In [1]:
import torch

In [2]:
x = torch.tensor([1,2,3,4,5],dtype = torch.float32)
print(x.shape)
y = x.repeat_interleave(x.shape[0]).reshape((-1,x.shape[0])).to(torch.float32)
print(y.shape)
print(y)

torch.Size([5])
torch.Size([5, 5])
tensor([[1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5.]])


In [3]:
k = torch.nn.functional.softmax(y,dim = 0)
print(k)
k = torch.nn.functional.softmax(y,dim = 1)
print(k)

tensor([[0.0117, 0.0117, 0.0117, 0.0117, 0.0117],
        [0.0317, 0.0317, 0.0317, 0.0317, 0.0317],
        [0.0861, 0.0861, 0.0861, 0.0861, 0.0861],
        [0.2341, 0.2341, 0.2341, 0.2341, 0.2341],
        [0.6364, 0.6364, 0.6364, 0.6364, 0.6364]])
tensor([[0.2000, 0.2000, 0.2000, 0.2000, 0.2000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000]])


In [7]:
a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
b = torch.tensor([1,2,3])
print(a + b)

tensor([[ 2,  4,  6],
        [ 5,  7,  9],
        [ 8, 10, 12]])
